plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.wavelengthmp3'
version = '0.1.0'

android {
  ndkVersion "29.0.14206865"
  namespace "expo.modules.wavelengthmp3"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
    externalNativeBuild {
      cmake {
        arguments "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON"
      }
    }
  }
  lintOptions {
    abortOnError false
  }
  externalNativeBuild {
    cmake {
      path "src/main/cpp/CMakeLists.txt"
      version "3.22.1"
    }
  }
}
